version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      # Gom tất cả update minor & patch vào 1 PR chung
      non-breaking:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      # Gom tất cả security update minor & patch vào 1 PR chung
      non-breaking-security:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
